version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expo-setup-app
    tty: true
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    volumes:
      - .:/usr/src
    stdin_open: true
    environment:
      - NODE_ENV=development
      - REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME}
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0